import { AnimatePresence, motion } from "framer-motion";
import { GraduationCap, Settings } from "lucide-react";
import { Component, type ReactNode } from "react";
import { SettingsView } from "../features/settings/SettingsView";
import { StudyView } from "../features/study/StudyView";
import { useUiStore } from "../stores/ui-store";
const destinations = [{ id: "study", label: "Study", icon: GraduationCap }, { id: "settings", label: "Settings", icon: Settings }] as const;
export class AppErrorBoundary extends Component<{ children: ReactNode }, { failed: boolean }> { override state = { failed: false }; static getDerivedStateFromError(): { failed: boolean } { return { failed: true }; } override render() { return this.state.failed ? <main className="grid min-h-screen place-items-center p-6"><div><h1 className="text-xl font-semibold">ClassMate AI needs a refresh</h1><p className="mt-2 text-muted-foreground">Your saved work is safe. Close and reopen the Side Panel.</p></div></main> : this.props.children; } }
export function App() { const view = useUiStore((state) => state.view); const setView = useUiStore((state) => state.setView); return <AppErrorBoundary><div className="min-h-screen pb-18 md:ps-18 md:pb-0"><header className="sticky top-0 z-20 border-b border-border bg-background/80 px-4 py-3 backdrop-blur-xl"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary font-bold text-primary-foreground">C</div><div><h1 className="text-sm font-bold">ClassMate AI</h1><p className="text-xs text-muted-foreground">Your personal study copilot</p></div><span className="ms-auto flex items-center gap-1.5 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-success"/>Local first</span></div></header><AnimatePresence mode="wait"><motion.main key={view} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: .16 }} className="mx-auto max-w-3xl p-3 sm:p-4 md:p-5">{view === "settings" ? <SettingsView /> : <StudyView />}</motion.main></AnimatePresence><nav aria-label="Primary" className="fixed inset-x-0 bottom-0 z-30 flex border-t border-border bg-surface-1/95 backdrop-blur-xl md:inset-y-0 md:end-auto md:w-18 md:flex-col md:border-e md:border-t-0 md:pt-20">{destinations.map(({ id, label, icon: Icon }) => <button key={id} type="button" aria-current={view === id ? "page" : undefined} onClick={() => setView(id)} className={`flex min-h-14 flex-1 flex-col items-center justify-center gap-1 text-[11px] outline-none focus-visible:ring-2 focus-visible:ring-ring md:flex-none ${view === id ? "text-primary" : "text-muted-foreground hover:text-foreground"}`}><Icon className="size-5"/><span>{label}</span></button>)}</nav></div></AppErrorBoundary>; }
