import { z } from "zod";

export const IdSchema = z.string().uuid();
export const SourceTypeSchema = z.enum(["article", "documentation", "repository", "pdf", "youtube", "image", "lms", "generic", "pasted"]);
export type SourceType = z.infer<typeof SourceTypeSchema>;
export const ContentBlockSchema = z.object({
  id: z.string().min(1), type: z.enum(["heading", "paragraph", "code", "list", "table", "quote"]),
  text: z.string().max(100_000), headingPath: z.array(z.string()).max(12), startOffset: z.number().int().nonnegative(),
  endOffset: z.number().int().nonnegative(), language: z.string().max(32).optional()
}).refine((value) => value.endOffset >= value.startOffset, "Invalid source offsets");
export type ContentBlock = z.infer<typeof ContentBlockSchema>;
export const SourceSnapshotSchema = z.object({
  schemaVersion: z.literal(1), id: IdSchema, title: z.string().min(1).max(500), canonicalUrl: z.string().url().optional(),
  sourceType: SourceTypeSchema, capturedAt: z.string().datetime(), contentHash: z.string().min(16),
  language: z.string().min(2).max(32).default("und"), blocks: z.array(ContentBlockSchema).max(10_000),
  scope: z.enum(["selection", "section", "page", "transcript", "pdf_pages", "image", "pasted"]),
  sensitivity: z.enum(["clear", "review", "blocked"])
});
export type SourceSnapshot = z.infer<typeof SourceSnapshotSchema>;

export const BoundingBoxSchema = z.tuple([z.number(), z.number(), z.number(), z.number()]);
export type BoundingBox = z.infer<typeof BoundingBoxSchema>;

export const OcrRegionSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1).max(10_000),
  confidence: z.number().min(0).max(1).optional(),
  boundingBox: BoundingBoxSchema.optional(),
  blockType: z.enum(["heading", "paragraph", "table", "caption"]).default("paragraph"),
  pageNumber: z.number().int().positive().optional(),
});
export type OcrRegion = z.infer<typeof OcrRegionSchema>;

export const TranscriptSegmentSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1).max(10_000),
  startMs: z.number().int().nonnegative(),
  durationMs: z.number().int().nonnegative().optional(),
  language: z.string().min(2).max(32).optional(),
  chapterTitle: z.string().min(1).max(500).optional(),
});
export type TranscriptSegment = z.infer<typeof TranscriptSegmentSchema>;

export const TranscriptTrackSchema = z.object({
  id: z.string().min(1),
  language: z.string().min(2).max(32),
  label: z.string().min(1).max(200),
  isAutoGenerated: z.boolean().default(false),
  isDefault: z.boolean().default(false),
});
export type TranscriptTrack = z.infer<typeof TranscriptTrackSchema>;

export const VideoChapterSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1).max(500),
  startMs: z.number().int().nonnegative(),
  endMs: z.number().int().nonnegative().optional(),
});
export type VideoChapter = z.infer<typeof VideoChapterSchema>;

export const PdfOutlineItemSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1).max(500),
  pageNumber: z.number().int().positive(),
  depth: z.number().int().nonnegative(),
});
export type PdfOutlineItem = z.infer<typeof PdfOutlineItemSchema>;

export const SourceAnchorSchema = z.object({
  blockId: z.string().min(1).optional(),
  quote: z.string().max(1000).optional(),
  pageNumber: z.number().int().positive().optional(),
  timestampMs: z.number().int().nonnegative().optional(),
  durationMs: z.number().int().nonnegative().optional(),
  boundingBox: BoundingBoxSchema.optional(),
  startOffset: z.number().int().nonnegative().optional(),
  endOffset: z.number().int().nonnegative().optional(),
});
export type SourceAnchor = z.infer<typeof SourceAnchorSchema>;

export const SourceAnnotationKindSchema = z.enum(["highlight", "underline", "note", "bookmark", "drawing", "selection_note", "page_comment"]);
export type SourceAnnotationKind = z.infer<typeof SourceAnnotationKindSchema>;

export const SourceAnnotationSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  sourceId: IdSchema,
  kind: SourceAnnotationKindSchema,
  text: z.string().max(5000).optional(),
  color: z.string().max(32).optional(),
  anchor: SourceAnchorSchema,
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type SourceAnnotation = z.infer<typeof SourceAnnotationSchema>;

export const StudyActionSchema = z.enum(["summary", "explain_simple", "explain_deep", "rewrite", "simplify", "flashcards", "quiz", "memory_tricks", "mind_map", "study_plan", "exam_answer", "university_answer", "lab_record", "viva", "chat", "smart_note", "exam"]);
export type StudyAction = z.infer<typeof StudyActionSchema>;

export const FlashcardTypeSchema = z.enum(["qa", "cloze", "definition", "concept", "formula"]);
export type FlashcardType = z.infer<typeof FlashcardTypeSchema>;

export const FlashcardSchema = z.object({
  id: z.string().uuid(),
  type: FlashcardTypeSchema,
  front: z.string().min(1).max(1000),
  back: z.string().min(1).max(2000),
  difficulty: z.enum(["easy", "medium", "hard"]),
  tags: z.array(z.string().max(50)).max(10),
  citations: z.array(z.string()),
  isFavorite: z.boolean().default(false),
  reviewCount: z.number().int().nonnegative().default(0),
  lastReviewedAt: z.string().datetime().optional(),
});
export type Flashcard = z.infer<typeof FlashcardSchema>;

export const FlashcardDeckSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.string().uuid(),
  title: z.string().min(1).max(500),
  sourceId: z.string().uuid().optional(),
  cards: z.array(FlashcardSchema).max(500),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type FlashcardDeck = z.infer<typeof FlashcardDeckSchema>;

export const QuestionTypeSchema = z.enum(["multiple_choice", "true_false", "fill_blank", "matching", "one_word", "short_answer", "long_answer", "essay", "assertion_reason", "case_study"]);
export type QuestionType = z.infer<typeof QuestionTypeSchema>;

export const QuizQuestionSchema = z.object({
  id: z.string().uuid(),
  type: QuestionTypeSchema,
  prompt: z.string().min(1).max(2000),
  choices: z.array(z.string().max(500)).max(6).optional(),
  correctAnswer: z.union([z.string(), z.array(z.string())]),
  explanation: z.string().max(1000).optional(),
  difficulty: z.enum(["easy", "medium", "hard"]),
  citations: z.array(z.string()),
});
export type QuizQuestion = z.infer<typeof QuizQuestionSchema>;

export const QuizAttemptSchema = z.object({
  id: z.string().uuid(),
  quizId: z.string().uuid(),
  answers: z.record(z.string(), z.union([z.string(), z.array(z.string())])),
  score: z.number().min(0).max(100),
  completedAt: z.string().datetime(),
});
export type QuizAttempt = z.infer<typeof QuizAttemptSchema>;

export const QuizSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.string().uuid(),
  title: z.string().min(1).max(500),
  sourceId: z.string().uuid().optional(),
  questions: z.array(QuizQuestionSchema).max(100),
  attempts: z.array(QuizAttemptSchema).max(50),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Quiz = z.infer<typeof QuizSchema>;

export const MemoryToolTypeSchema = z.enum(["mnemonic", "acronym", "analogy", "story", "feynman"]);
export type MemoryToolType = z.infer<typeof MemoryToolTypeSchema>;

export const MemoryAidSchema = z.object({
  id: z.string().uuid(),
  type: MemoryToolTypeSchema,
  concept: z.string().min(1).max(500),
  aid: z.string().min(1).max(2000),
  explanation: z.string().max(1000).optional(),
  citations: z.array(z.string()),
});
export type MemoryAid = z.infer<typeof MemoryAidSchema>;

export const MindMapNodeSchema = z.object({
  id: z.string().uuid(),
  label: z.string().min(1).max(200),
  parentId: z.string().uuid().nullable(),
  children: z.array(z.string().uuid()),
  level: z.number().int().nonnegative(),
  isExpanded: z.boolean().default(true),
});
export type MindMapNode = z.infer<typeof MindMapNodeSchema>;

export const MindMapSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.string().uuid(),
  title: z.string().min(1).max(500),
  sourceId: z.string().uuid().optional(),
  nodes: z.array(MindMapNodeSchema).max(200),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type MindMap = z.infer<typeof MindMapSchema>;

export const StudyPlanTypeSchema = z.enum(["30_min", "1_hour", "tomorrow_exam", "one_week"]);
export type StudyPlanType = z.infer<typeof StudyPlanTypeSchema>;

export const StudyPlanItemSchema = z.object({
  id: z.string().uuid(),
  title: z.string().min(1).max(300),
  duration: z.number().int().positive(),
  order: z.number().int().nonnegative(),
  topics: z.array(z.string().max(200)).max(10),
});
export type StudyPlanItem = z.infer<typeof StudyPlanItemSchema>;

export const StudyPlanSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.string().uuid(),
  title: z.string().min(1).max(500),
  planType: StudyPlanTypeSchema,
  sourceId: z.string().uuid().optional(),
  items: z.array(StudyPlanItemSchema).max(20),
  totalDuration: z.number().int().positive(),
  createdAt: z.string().datetime(),
});
export type StudyPlan = z.infer<typeof StudyPlanSchema>;

export const CitationSchema = z.object({ id: z.string(), sourceId: IdSchema, chunkId: z.string(), quote: z.string().max(1000).optional(), confidence: z.enum(["high", "medium", "low"]) });
export type Citation = z.infer<typeof CitationSchema>;

export const NoteBlockTypeSchema = z.enum(["markdown", "heading", "paragraph", "list", "table", "image", "code", "callout", "math", "link", "checkbox", "quote", "hr", "embed_pdf", "embed_youtube", "embed_image"]);
export type NoteBlockType = z.infer<typeof NoteBlockTypeSchema>;

export const NoteStatusSchema = z.enum(["active", "archived", "trashed"]);
export type NoteStatus = z.infer<typeof NoteStatusSchema>;

export const NoteKindSchema = z.enum(["manual", "summary", "detailed", "class", "lecture", "revision", "formula_sheet", "cheat_sheet", "one_page_revision", "concept", "definition"]);
export type NoteKind = z.infer<typeof NoteKindSchema>;

export const NoteTagSchema = z.object({
  id: IdSchema,
  label: z.string().min(1).max(80),
  color: z.string().max(32).optional(),
  kind: z.enum(["manual", "automatic", "topic", "difficulty", "subject"]),
});
export type NoteTag = z.infer<typeof NoteTagSchema>;

export const NoteBlockSchema = z.object({
  id: IdSchema,
  type: NoteBlockTypeSchema,
  markdown: z.string().max(100_000),
  metadata: z.record(z.string(), z.string()).default({}),
});
export type NoteBlock = z.infer<typeof NoteBlockSchema>;

export const NoteVersionSchema = z.object({
  id: IdSchema,
  noteId: IdSchema,
  markdown: z.string().max(500_000),
  savedAt: z.string().datetime(),
  reason: z.enum(["autosave", "manual", "ai_generation", "import"]),
});
export type NoteVersion = z.infer<typeof NoteVersionSchema>;

export const SmartNoteSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  title: z.string().min(1).max(500),
  kind: NoteKindSchema,
  markdown: z.string().max(500_000),
  blocks: z.array(NoteBlockSchema).max(1000),
  folderId: IdSchema.optional(),
  collectionIds: z.array(IdSchema).default([]),
  sourceIds: z.array(IdSchema).default([]),
  referencedArtifactIds: z.array(IdSchema).default([]),
  tags: z.array(NoteTagSchema).max(50).default([]),
  citations: z.array(CitationSchema).default([]),
  linkedNoteIds: z.array(IdSchema).default([]),
  isPinned: z.boolean().default(false),
  isFavorite: z.boolean().default(false),
  status: NoteStatusSchema.default("active"),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  lastOpenedAt: z.string().datetime().optional(),
  versions: z.array(NoteVersionSchema).max(100).default([]),
});
export type SmartNote = z.infer<typeof SmartNoteSchema>;

export const NoteFolderSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  name: z.string().min(1).max(120),
  parentId: IdSchema.nullable(),
  color: z.string().max(32).optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type NoteFolder = z.infer<typeof NoteFolderSchema>;

export const NoteCollectionSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  name: z.string().min(1).max(160),
  noteIds: z.array(IdSchema).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type NoteCollection = z.infer<typeof NoteCollectionSchema>;

export const KnowledgeGraphNodeSchema = z.object({
  id: IdSchema,
  label: z.string().min(1).max(200),
  kind: z.enum(["note", "source", "pdf", "youtube", "website", "topic", "artifact"]),
  refId: z.string().min(1),
  weight: z.number().nonnegative().default(1),
  isExpanded: z.boolean().default(true),
});
export type KnowledgeGraphNode = z.infer<typeof KnowledgeGraphNodeSchema>;

export const KnowledgeGraphEdgeSchema = z.object({
  id: IdSchema,
  fromId: IdSchema,
  toId: IdSchema,
  label: z.string().max(120),
  strength: z.number().min(0).max(1),
});
export type KnowledgeGraphEdge = z.infer<typeof KnowledgeGraphEdgeSchema>;

export const KnowledgeGraphSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  title: z.string().min(1).max(300),
  nodes: z.array(KnowledgeGraphNodeSchema).max(2000),
  edges: z.array(KnowledgeGraphEdgeSchema).max(5000),
  updatedAt: z.string().datetime(),
});
export type KnowledgeGraph = z.infer<typeof KnowledgeGraphSchema>;

export const ExamTypeSchema = z.enum(["practice_test", "mock_exam", "previous_year_style", "topic_exam", "subject_exam", "mixed_exam", "timed_exam"]);
export type ExamType = z.infer<typeof ExamTypeSchema>;

export const ExamQuestionSchema = QuizQuestionSchema.extend({
  marks: z.number().int().positive().max(100),
  topic: z.string().max(160).optional(),
  expectedTimeMinutes: z.number().int().positive().optional(),
});
export type ExamQuestion = z.infer<typeof ExamQuestionSchema>;

export const ExamSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  title: z.string().min(1).max(500),
  type: ExamTypeSchema,
  subject: z.string().max(160).optional(),
  sourceIds: z.array(IdSchema).default([]),
  questions: z.array(ExamQuestionSchema).max(200),
  durationMinutes: z.number().int().positive(),
  totalMarks: z.number().int().positive(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Exam = z.infer<typeof ExamSchema>;

export const ExamAnswerEvaluationSchema = z.object({
  questionId: IdSchema,
  score: z.number().min(0).max(100),
  earnedMarks: z.number().min(0),
  feedback: z.string().max(2000),
  mistakes: z.array(z.string().max(300)).default([]),
  confidence: z.number().min(0).max(1),
});
export type ExamAnswerEvaluation = z.infer<typeof ExamAnswerEvaluationSchema>;

export const ExamResultSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  examId: IdSchema,
  answers: z.record(IdSchema, z.string().max(20_000)),
  evaluations: z.array(ExamAnswerEvaluationSchema),
  score: z.number().min(0).max(100),
  weakTopics: z.array(z.string().max(160)).default([]),
  strongTopics: z.array(z.string().max(160)).default([]),
  difficultyAnalysis: z.record(z.enum(["easy", "medium", "hard"]), z.number()).default({ easy: 0, medium: 0, hard: 0 }),
  coverageAnalysis: z.array(z.string().max(300)).default([]),
  completedAt: z.string().datetime(),
});
export type ExamResult = z.infer<typeof ExamResultSchema>;

export const AnalyticsActivitySchema = z.object({
  id: IdSchema,
  kind: z.enum(["study_session", "note_edit", "quiz_attempt", "exam_attempt", "revision", "artifact_created"]),
  topic: z.string().max(160).optional(),
  subject: z.string().max(160).optional(),
  durationMinutes: z.number().int().nonnegative(),
  accuracy: z.number().min(0).max(100).optional(),
  completed: z.boolean().default(true),
  occurredAt: z.string().datetime(),
});
export type AnalyticsActivity = z.infer<typeof AnalyticsActivitySchema>;

export const LearningAnalyticsSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  activities: z.array(AnalyticsActivitySchema).max(10_000),
  studyTimeMinutes: z.number().int().nonnegative(),
  streakDays: z.number().int().nonnegative(),
  accuracy: z.number().min(0).max(100),
  completion: z.number().min(0).max(100),
  revisionFrequency: z.number().nonnegative(),
  topicMastery: z.record(z.string(), z.number().min(0).max(100)),
  subjectMastery: z.record(z.string(), z.number().min(0).max(100)),
  updatedAt: z.string().datetime(),
});
export type LearningAnalytics = z.infer<typeof LearningAnalyticsSchema>;

export const RevisionItemSchema = z.object({
  id: IdSchema,
  title: z.string().min(1).max(300),
  topic: z.string().max(160),
  sourceId: IdSchema.optional(),
  priority: z.enum(["low", "medium", "high"]),
  dueAt: z.string().datetime(),
  intervalDays: z.number().int().positive(),
  completedAt: z.string().datetime().optional(),
});
export type RevisionItem = z.infer<typeof RevisionItemSchema>;

export const RevisionPlanSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  examTitle: z.string().max(300).optional(),
  examDate: z.string().datetime().optional(),
  items: z.array(RevisionItemSchema).max(1000),
  recommendations: z.array(z.string().max(300)).default([]),
  updatedAt: z.string().datetime(),
});
export type RevisionPlan = z.infer<typeof RevisionPlanSchema>;

export const EmbeddingVectorSchema = z.array(z.number()).min(8).max(4096);
export type EmbeddingVector = z.infer<typeof EmbeddingVectorSchema>;

export const EmbeddingRecordSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  sourceId: IdSchema,
  chunkId: z.string().min(1),
  contentHash: z.string().min(16),
  text: z.string().max(100_000),
  headingPath: z.array(z.string()).max(12).default([]),
  citations: z.array(CitationSchema).default([]),
  vector: EmbeddingVectorSchema,
  model: z.string().min(1).max(120),
  createdAt: z.string().datetime(),
});
export type EmbeddingRecord = z.infer<typeof EmbeddingRecordSchema>;

export const RetrievalEvidenceSchema = z.object({
  id: IdSchema,
  sourceId: IdSchema,
  chunkId: z.string().min(1),
  title: z.string().max(500),
  text: z.string().max(20_000),
  score: z.number().min(0).max(1),
  keywordScore: z.number().min(0).max(1),
  vectorScore: z.number().min(0).max(1),
  headingPath: z.array(z.string()).max(12).default([]),
  citations: z.array(CitationSchema).default([]),
});
export type RetrievalEvidence = z.infer<typeof RetrievalEvidenceSchema>;

export const RetrievalCacheEntrySchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  queryHash: z.string().min(16),
  query: z.string().max(10_000),
  evidence: z.array(RetrievalEvidenceSchema).max(100),
  createdAt: z.string().datetime(),
});
export type RetrievalCacheEntry = z.infer<typeof RetrievalCacheEntrySchema>;

export const SemanticClusterSchema = z.object({
  id: IdSchema,
  label: z.string().min(1).max(200),
  recordIds: z.array(IdSchema).min(1),
  centroid: EmbeddingVectorSchema,
  similarity: z.number().min(0).max(1),
});
export type SemanticCluster = z.infer<typeof SemanticClusterSchema>;

export const OfflineAiModeSchema = z.enum(["online", "offline", "auto"]);
export type OfflineAiMode = z.infer<typeof OfflineAiModeSchema>;

export const SyncEntityTypeSchema = z.enum(["source", "artifact", "note", "flashcard_deck", "quiz", "study_plan", "folder", "workspace", "knowledge_graph"]);
export type SyncEntityType = z.infer<typeof SyncEntityTypeSchema>;

export const SyncOperationTypeSchema = z.enum(["create", "update", "delete", "restore", "share", "comment"]);
export type SyncOperationType = z.infer<typeof SyncOperationTypeSchema>;

export const SyncOperationStatusSchema = z.enum(["pending", "syncing", "acked", "failed", "conflict"]);
export type SyncOperationStatus = z.infer<typeof SyncOperationStatusSchema>;

export const SyncDeviceSchema = z.object({
  id: IdSchema,
  name: z.string().min(1).max(120),
  lastSeenAt: z.string().datetime(),
  publicKeyFingerprint: z.string().max(160).optional(),
});
export type SyncDevice = z.infer<typeof SyncDeviceSchema>;

export const SyncDeltaSchema = z.object({
  path: z.string().min(1).max(500),
  before: z.unknown().optional(),
  after: z.unknown().optional(),
});
export type SyncDelta = z.infer<typeof SyncDeltaSchema>;

export const SyncOperationSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  entityType: SyncEntityTypeSchema,
  entityId: IdSchema,
  operation: SyncOperationTypeSchema,
  baseVersionId: IdSchema.optional(),
  localVersionId: IdSchema.optional(),
  remoteVersionId: IdSchema.optional(),
  delta: z.array(SyncDeltaSchema).max(500),
  status: SyncOperationStatusSchema,
  retryCount: z.number().int().nonnegative().default(0),
  deviceId: IdSchema,
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  lastError: z.string().max(1000).optional(),
});
export type SyncOperation = z.infer<typeof SyncOperationSchema>;

export const SyncMetadataSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  deviceId: IdSchema,
  lastPulledAt: z.string().datetime().optional(),
  lastPushedAt: z.string().datetime().optional(),
  cursor: z.string().max(500).optional(),
  online: z.boolean().default(false),
  pendingCount: z.number().int().nonnegative().default(0),
  conflictCount: z.number().int().nonnegative().default(0),
  updatedAt: z.string().datetime(),
});
export type SyncMetadata = z.infer<typeof SyncMetadataSchema>;

export const ConflictResolutionSchema = z.enum(["use_local", "use_remote", "merge", "keep_both"]);
export type ConflictResolution = z.infer<typeof ConflictResolutionSchema>;

export const SyncConflictSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  operationId: IdSchema,
  entityType: SyncEntityTypeSchema,
  entityId: IdSchema,
  localVersionId: IdSchema,
  remoteVersionId: IdSchema,
  baseVersionId: IdSchema.optional(),
  fields: z.array(z.string().max(500)).default([]),
  status: z.enum(["open", "resolved"]),
  resolution: ConflictResolutionSchema.optional(),
  createdAt: z.string().datetime(),
  resolvedAt: z.string().datetime().optional(),
});
export type SyncConflict = z.infer<typeof SyncConflictSchema>;

export const VersionSnapshotSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  entityType: SyncEntityTypeSchema,
  entityId: IdSchema,
  parentVersionId: IdSchema.optional(),
  payload: z.unknown(),
  hash: z.string().min(16),
  label: z.string().max(200).optional(),
  authorDeviceId: IdSchema,
  createdAt: z.string().datetime(),
});
export type VersionSnapshot = z.infer<typeof VersionSnapshotSchema>;

export const CollaborationRoleSchema = z.enum(["owner", "editor", "commenter", "viewer"]);
export type CollaborationRole = z.infer<typeof CollaborationRoleSchema>;

export const CollaboratorSchema = z.object({
  id: IdSchema,
  displayName: z.string().min(1).max(120),
  role: CollaborationRoleSchema,
  invitedAt: z.string().datetime(),
  acceptedAt: z.string().datetime().optional(),
});
export type Collaborator = z.infer<typeof CollaboratorSchema>;

export const SharedWorkspaceSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  title: z.string().min(1).max(300),
  entityType: SyncEntityTypeSchema,
  entityIds: z.array(IdSchema).default([]),
  collaborators: z.array(CollaboratorSchema).max(100),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type SharedWorkspace = z.infer<typeof SharedWorkspaceSchema>;

export const CollaborationCommentSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  workspaceId: IdSchema,
  entityId: IdSchema.optional(),
  authorId: IdSchema,
  body: z.string().min(1).max(5000),
  createdAt: z.string().datetime(),
  resolvedAt: z.string().datetime().optional(),
});
export type CollaborationComment = z.infer<typeof CollaborationCommentSchema>;

export const ActivityFeedEventSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  workspaceId: IdSchema.optional(),
  actorId: IdSchema,
  verb: z.enum(["created", "updated", "deleted", "shared", "commented", "resolved_conflict", "restored"]),
  entityType: SyncEntityTypeSchema,
  entityId: IdSchema,
  summary: z.string().min(1).max(500),
  createdAt: z.string().datetime(),
});
export type ActivityFeedEvent = z.infer<typeof ActivityFeedEventSchema>;

export const BackupMetadataSchema = z.object({
  schemaVersion: z.literal(1),
  id: IdSchema,
  label: z.string().min(1).max(200),
  recordCount: z.number().int().nonnegative(),
  byteSize: z.number().int().nonnegative(),
  createdAt: z.string().datetime(),
  restoredAt: z.string().datetime().optional(),
});
export type BackupMetadata = z.infer<typeof BackupMetadataSchema>;

export const ArtifactSchema = z.object({
  schemaVersion: z.literal(1), id: IdSchema, type: StudyActionSchema, title: z.string().min(1).max(500), markdown: z.string(),
  citations: z.array(CitationSchema), sourceIds: z.array(IdSchema), createdAt: z.string().datetime(),
  provenance: z.object({ provider: z.enum(["gemini", "groq", "openrouter", "ollama"]), model: z.string(), templateId: z.string(), templateVersion: z.string(), isAiGenerated: z.literal(true) })
});
export type Artifact = z.infer<typeof ArtifactSchema>;

export const ProviderIdSchema = z.enum(["gemini", "groq", "openrouter", "ollama"]);
export type ProviderId = z.infer<typeof ProviderIdSchema>;
export const GenerationRequestSchema = z.object({
  schemaVersion: z.literal(1), operationId: IdSchema, action: StudyActionSchema, prompt: z.string().max(20_000),
  source: SourceSnapshotSchema, providerId: ProviderIdSchema.optional(), modelId: z.string().optional(),
  settings: z.object({ depth: z.enum(["brief", "standard", "deep"]), locale: z.string(), marks: z.union([z.literal(2), z.literal(5), z.literal(10), z.literal(16)]).optional(), allowPaid: z.boolean().default(false) })
});
export type GenerationRequest = z.infer<typeof GenerationRequestSchema>;
export const StreamEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("phase"), sequence: z.number().int(), phase: z.enum(["preparing", "routing", "streaming", "validating"]) }),
  z.object({ type: z.literal("delta"), sequence: z.number().int(), text: z.string() }),
  z.object({ type: z.literal("warning"), sequence: z.number().int(), message: z.string() }),
  z.object({ type: z.literal("complete"), sequence: z.number().int(), finishReason: z.enum(["stop", "length"]) }),
  z.object({ type: z.literal("error"), sequence: z.number().int(), code: z.string(), message: z.string(), retryable: z.boolean() })
]);
export type StreamEvent = z.infer<typeof StreamEventSchema>;

export const ExtensionMessageSchema = z.discriminatedUnion("type", [
  z.object({ version: z.literal(1), type: z.literal("CAPTURE_CONTEXT"), requestId: IdSchema, scope: z.enum(["selection", "page"]) }),
  z.object({ version: z.literal(1), type: z.literal("OPEN_SIDE_PANEL"), requestId: IdSchema })
]);
export type ExtensionMessage = z.infer<typeof ExtensionMessageSchema>;

export const SettingsSchema = z.object({
  schemaVersion: z.literal(1),
  theme: z.enum(["dark", "light", "system"]),
  locale: z.string().min(2).max(32),
  defaultProvider: ProviderIdSchema,
  explanationDepth: z.enum(["brief", "standard", "deep"]),
  telemetryConsent: z.boolean(),
});
export type Settings = z.infer<typeof SettingsSchema>;
