import {
  extractFromImageOcr,
  extractFromPdfPages,
  extractFromYoutubePageData,
  type OcrRegionInput,
  type PdfPageInput,
  type YoutubeChapterInput,
  type YoutubeSegmentInput,
  type YoutubeTrackInput,
} from "@classmate/content-core";
import type { SourceSnapshot } from "@classmate/contracts";
import {
  createOcrRegion,
  createPdfOutlineItem,
  createStoredSourceDocument,
  createTranscriptSegment,
  createTranscriptTrack,
  createVideoChapter,
  type ImageSourcePayload,
  type PdfSourcePayload,
  type StoredSourceDocument,
  type YoutubeSourcePayload,
} from "../../features/workspace/sourceDocuments";

const PDF_URL_RE = /\.pdf(?:$|[?#])/i;
const IMAGE_URL_RE = /\.(png|jpe?g|webp)(?:$|[?#])/i;
const YOUTUBE_HOST_RE = /(^|\.)youtube\.com$|(^|\.)youtu\.be$/i;

export interface CapturedUniversalSource {
  source: SourceSnapshot;
  document: StoredSourceDocument;
}

export async function capturePdfSourceFromUrl(url: string, title: string): Promise<CapturedUniversalSource> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("The PDF could not be downloaded.");
  }
  return capturePdfSourceFromBytes(await response.arrayBuffer(), title, url);
}

export async function capturePdfSourceFromFile(file: File): Promise<CapturedUniversalSource> {
  return capturePdfSourceFromBytes(await file.arrayBuffer(), file.name.replace(/\.pdf$/i, ""), `file:${file.name}`);
}

export async function captureImageSourceFromUrl(url: string, title: string): Promise<CapturedUniversalSource> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("The image could not be downloaded.");
  }
  const blob = await response.blob();
  return captureImageSourceFromBlob(blob, title, url);
}

export async function captureImageSourceFromFile(file: File): Promise<CapturedUniversalSource> {
  return captureImageSourceFromBlob(file, file.name, `file:${file.name}`);
}

export async function captureYoutubeSourceFromUrl(url: string, title: string): Promise<CapturedUniversalSource> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("The YouTube page could not be loaded.");
  }
  const html = await response.text();
  const pageData = parseYoutubePageData(url, html);
  const activeTrack = pageData.tracks.find((track) => track.isDefault) ?? pageData.tracks[0];
  if (!activeTrack?.sourceUrl) {
    throw new Error("No permitted transcript is available for this video.");
  }
  const transcriptResponse = await fetch(activeTrack.sourceUrl);
  if (!transcriptResponse.ok) {
    throw new Error("The YouTube transcript could not be loaded.");
  }
  const segments = parseYoutubeTranscriptXml(await transcriptResponse.text(), activeTrack.language);
  const extraction = await extractFromYoutubePageData(
    url,
    pageData.title || title,
    segments.map((segment) => ({
      text: segment.text,
      startMs: segment.startMs,
      durationMs: segment.durationMs,
      language: segment.language,
      chapterTitle: segment.chapterTitle,
    })),
    pageData.chapters,
    pageData.tracks.map((track) => ({
      id: track.id,
      language: track.language,
      label: track.label,
      isAutoGenerated: track.isAutoGenerated,
      isDefault: track.isDefault,
    })),
    pageData.description,
  );
  const payload: YoutubeSourcePayload = {
    kind: "youtube",
    title: extraction.snapshot.title,
    url,
    videoId: pageData.videoId,
    embedUrl: `https://www.youtube-nocookie.com/embed/${pageData.videoId}`,
    description: pageData.description,
    channelTitle: pageData.channelTitle,
    thumbnailUrl: pageData.thumbnailUrl,
    chapters: pageData.chapters.map((chapter) =>
      createVideoChapter({
        id: chapter.id,
        title: chapter.title,
        startMs: chapter.startMs,
        endMs: chapter.endMs,
      }),
    ),
    tracks: pageData.tracks.map((track) =>
      createTranscriptTrack({
        id: track.id,
        language: track.language,
        label: track.label,
        isAutoGenerated: track.isAutoGenerated,
        isDefault: track.isDefault,
      }),
    ),
    activeTrackId: activeTrack.id,
    segments: segments.map((segment) =>
      createTranscriptSegment({
        id: segment.id,
        text: segment.text,
        startMs: segment.startMs,
        durationMs: segment.durationMs,
        language: segment.language,
        chapterTitle: segment.chapterTitle,
      }),
    ),
  };
  return {
    source: extraction.snapshot,
    document: createStoredSourceDocument({
      sourceId: extraction.snapshot.id,
      title: extraction.snapshot.title,
      url,
      payload,
    }),
  };
}

export function isPdfUrl(url: string): boolean {
  return PDF_URL_RE.test(url);
}

export function isImageUrl(url: string): boolean {
  return IMAGE_URL_RE.test(url);
}

export function isYoutubeUrl(url: string): boolean {
  try {
    return YOUTUBE_HOST_RE.test(new URL(url).hostname);
  } catch {
    return false;
  }
}

export interface ParsedYoutubeTrack extends YoutubeTrackInput {
  sourceUrl?: string | undefined;
}

export interface ParsedYoutubeSegment extends YoutubeSegmentInput {
  id: string;
}

export interface ParsedYoutubeChapter extends YoutubeChapterInput {
  id: string;
}

export interface ParsedYoutubePageData {
  title: string;
  videoId: string;
  description?: string | undefined;
  channelTitle?: string | undefined;
  thumbnailUrl?: string | undefined;
  tracks: ParsedYoutubeTrack[];
  chapters: ParsedYoutubeChapter[];
}

export function parseYoutubePageData(url: string, html: string): ParsedYoutubePageData {
  const playerResponse = parseJsonAssignment(html, "ytInitialPlayerResponse");
  const initialData = parseJsonAssignment(html, "ytInitialData");
  const videoId = readString(playerResponse, ["videoDetails", "videoId"]) ?? new URL(url).searchParams.get("v") ?? "unknown";
  const title = readString(playerResponse, ["videoDetails", "title"]) ?? readString(initialData, ["metadata", "title"]) ?? "YouTube video";
  const description = readString(playerResponse, ["videoDetails", "shortDescription"]);
  const channelTitle = readString(playerResponse, ["videoDetails", "author"]);
  const thumbnailUrl = readNestedArrayString(playerResponse, ["videoDetails", "thumbnail", "thumbnails"]);
  const tracks = parseCaptionTracks(playerResponse);
  const chapters = extractDescriptionChapters(description);
  return { title, videoId, description, channelTitle, thumbnailUrl, tracks, chapters };
}

export function parseYoutubeTranscriptXml(
  xml: string,
  language: string,
  chapters: readonly YoutubeChapterInput[] = [],
): ParsedYoutubeSegment[] {
  const chapterFor = (startMs: number): string | undefined =>
    chapters
      .filter((chapter) => chapter.startMs <= startMs && (chapter.endMs === undefined || chapter.endMs >= startMs))
      .at(-1)?.title;
  const segments: ParsedYoutubeSegment[] = [];
  const regex = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  for (const match of xml.matchAll(regex)) {
    const attrs = match[1] ?? "";
    const text = decodeHtmlEntities(stripTags(match[2] ?? "")).trim();
    if (!text) continue;
    const start = Number.parseFloat(readXmlAttr(attrs, "start") ?? "0");
    const dur = Number.parseFloat(readXmlAttr(attrs, "dur") ?? "0");
    const startMs = Math.max(0, Math.round(start * 1000));
    segments.push({
      id: crypto.randomUUID(),
      text,
      startMs,
      durationMs: Number.isFinite(dur) ? Math.max(0, Math.round(dur * 1000)) : undefined,
      language,
      chapterTitle: chapterFor(startMs),
    });
  }
  return segments;
}

async function capturePdfSourceFromBytes(
  bytes: ArrayBuffer,
  title: string,
  url: string,
): Promise<CapturedUniversalSource> {
  const decodedText = extractTextFromPdfBytes(bytes);
  const pageTexts = splitPdfTextIntoPages(decodedText);
  const pages: PdfPageInput[] = [];
  for (const [index, pageText] of pageTexts.entries()) {
    const pageNumber = index + 1;
    const text = pageText.trim() || `Scanned or image-only PDF page ${String(pageNumber)}. Use OCR image capture for text extraction.`;
    pages.push({
      pageNumber,
      text,
      headings: inferPdfHeadings(text),
      links: extractLinksFromText(text, pageNumber),
      tables: inferPdfTables(text, pageNumber),
      images: [{ src: renderTextPreview(title, pageNumber, text), alt: `Page ${String(pageNumber)} preview`, pageNumber }],
      width: 612,
      height: 792,
    });
  }
  const extraction = await extractFromPdfPages(url, title, pages);
  const payload: PdfSourcePayload = {
    kind: "pdf",
    title: extraction.snapshot.title,
    url,
    keywords: inferPdfKeywords(decodedText),
    pageCount: pages.length,
    currentPage: 1,
    outline: pages.flatMap((page) =>
      (page.headings ?? []).map((heading, index) =>
        createPdfOutlineItem(heading, page.pageNumber, 0),
      ),
    ),
    pages: pages.map((page) => ({
      pageNumber: page.pageNumber,
      text: page.text,
      headings: [...(page.headings ?? [])],
      links: (page.links ?? []).map((link) => ({ href: link.href, text: link.text, pageNumber: link.pageNumber })),
      tables: (page.tables ?? []).map((table) => ({
        pageNumber: table.pageNumber,
        rows: table.rows.map((row) => [...row]),
        ...(table.headingPath ? { headingPath: [...table.headingPath] } : {}),
      })),
      images: (page.images ?? []).map((image) => ({
        src: image.src,
        alt: image.alt,
        pageNumber: image.pageNumber,
        ...(image.title ? { title: image.title } : {}),
        ...(image.caption ? { caption: image.caption } : {}),
      })),
      width: page.width,
      height: page.height,
      thumbnailDataUrl: page.images?.[0]?.src,
    })),
  };
  return {
    source: extraction.snapshot,
    document: createStoredSourceDocument({
      sourceId: extraction.snapshot.id,
      title: extraction.snapshot.title,
      url,
      payload,
    }),
  };
}

async function captureImageSourceFromBlob(
  blob: Blob,
  title: string,
  url: string,
): Promise<CapturedUniversalSource> {
  const image = await loadImage(blob);
  const canvas = document.createElement("canvas");
  canvas.width = image.naturalWidth;
  canvas.height = image.naturalHeight;
  const context = canvas.getContext("2d");
  if (!context) {
    throw new Error("The image canvas context is unavailable.");
  }
  context.drawImage(image, 0, 0);
  const ocr = runBrowserImageExtraction(canvas, title);
  const regions = ocr.regions.map((region) =>
    createOcrRegion({
      text: region.text,
      confidence: region.confidence,
      pageNumber: region.pageNumber,
      blockType: region.blockType,
      boundingBox: region.boundingBox ? [...region.boundingBox] : undefined,
    }),
  );
  const extraction = await extractFromImageOcr({
    url,
    title,
    text: ocr.text,
    captions: [title],
    layoutWidth: image.naturalWidth,
    layoutHeight: image.naturalHeight,
    regions,
  });
  const payload: ImageSourcePayload = {
    kind: "image",
    title: extraction.snapshot.title,
    url,
    mimeType: blob.type || undefined,
    width: image.naturalWidth,
    height: image.naturalHeight,
    captions: [title],
    ocrRegions: regions,
    previewDataUrl: canvas.toDataURL(blob.type || "image/png"),
  };
  return {
    source: extraction.snapshot,
    document: createStoredSourceDocument({
      sourceId: extraction.snapshot.id,
      title: extraction.snapshot.title,
      url,
      payload,
    }),
  };
}

function inferPdfHeadings(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+|\n+/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && line.length <= 80)
    .filter((line) => /^[A-Z][A-Za-z0-9 ,:;()/-]{2,}$/.test(line))
    .slice(0, 3);
}

function inferPdfKeywords(text: string): string[] {
  return [...new Set(text.toLowerCase().match(/\b[a-z][a-z0-9-]{4,}\b/g) ?? [])].slice(0, 12);
}

function extractLinksFromText(text: string, pageNumber: number) {
  return [...text.matchAll(/https?:\/\/[^\s)]+/g)].slice(0, 20).map((match) => ({
    href: match[0],
    text: match[0],
    pageNumber,
  }));
}

function inferPdfTables(text: string, pageNumber: number) {
  return text.includes("|")
    ? [{ pageNumber, rows: text.split("\n").filter((line) => line.includes("|")).map((line) => line.split("|").map((cell) => cell.trim())) }]
    : [];
}

function runBrowserImageExtraction(
  canvas: HTMLCanvasElement,
  title: string,
): { text: string; regions: OcrRegionInput[] } {
  const text = `${title}. Image metadata: ${String(canvas.width)} by ${String(canvas.height)} pixels.`;
  return {
    text,
    regions: [{
      text,
      confidence: 0.5,
      boundingBox: [0, 0, canvas.width, canvas.height],
      blockType: "caption",
    }],
  };
}

function extractTextFromPdfBytes(bytes: ArrayBuffer): string {
  return new TextDecoder("latin1").decode(bytes)
    .replace(/\0/g, " ")
    .replace(/\\[()]/g, "")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function splitPdfTextIntoPages(text: string): string[] {
  const markerSplit = text.split(/\f|\/Type\s*\/Page\b/g).map((page) => page.trim()).filter(Boolean);
  if (markerSplit.length > 1) return markerSplit.slice(0, 200);
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [""];
  const pages: string[] = [];
  for (let index = 0; index < words.length; index += 450) {
    pages.push(words.slice(index, index + 450).join(" "));
  }
  return pages.slice(0, 200);
}

function renderTextPreview(title: string, pageNumber: number, text: string): string {
  const canvas = document.createElement("canvas");
  canvas.width = 240;
  canvas.height = 320;
  const context = canvas.getContext("2d");
  if (!context) return "";
  context.fillStyle = "#111827";
  context.fillRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = "#f8fafc";
  context.font = "14px sans-serif";
  context.fillText(`${title} - ${String(pageNumber)}`, 16, 28);
  context.font = "11px monospace";
  const words = text.split(/\s+/).slice(0, 90);
  let line = "";
  let y = 54;
  for (const word of words) {
    const next = `${line} ${word}`.trim();
    if (context.measureText(next).width > 208) {
      context.fillText(line, 16, y);
      line = word;
      y += 16;
    } else {
      line = next;
    }
    if (y > 296) break;
  }
  if (line && y <= 296) context.fillText(line, 16, y);
  return canvas.toDataURL("image/png");
}

async function loadImage(blob: Blob): Promise<HTMLImageElement> {
  const objectUrl = URL.createObjectURL(blob);
  try {
    const image = new Image();
    image.decoding = "async";
    image.src = objectUrl;
    await image.decode();
    return image;
  } finally {
    URL.revokeObjectURL(objectUrl);
  }
}

function parseCaptionTracks(playerResponse: unknown): ParsedYoutubeTrack[] {
  const rawTracks = readUnknown(playerResponse, ["captions", "playerCaptionsTracklistRenderer", "captionTracks"]);
  if (!Array.isArray(rawTracks)) return [];
  return rawTracks
    .map((track): ParsedYoutubeTrack | undefined => {
      const baseUrl = readString(track, ["baseUrl"]);
      const languageCode = readString(track, ["languageCode"]);
      const label = readString(track, ["name", "simpleText"]) ?? languageCode;
      if (!baseUrl || !languageCode || !label) return undefined;
      return {
        id: languageCode,
        language: languageCode,
        label,
        isAutoGenerated: /asr/i.test(readString(track, ["kind"]) ?? ""),
        isDefault: Boolean(readUnknown(track, ["isTranslatable"])) || rawTracks[0] === track,
        sourceUrl: baseUrl,
      } satisfies ParsedYoutubeTrack;
    })
    .filter((track): track is ParsedYoutubeTrack => track !== undefined);
}

function extractDescriptionChapters(description: string | undefined): ParsedYoutubeChapter[] {
  if (!description) return [];
  return description
    .split("\n")
    .map((line) => line.trim())
    .map((line) => /^(\d{1,2}:\d{2}(?::\d{2})?)\s+(.+)$/.exec(line))
    .filter((match): match is RegExpExecArray => match !== null)
    .map((match, index, all) => {
      const [, timestamp = "0:00", title = "Chapter"] = match;
      const nextMatch = all[index + 1];
      const nextTimestamp = nextMatch?.[1];
      return {
        id: `chapter-${String(index + 1)}`,
        title: title.trim(),
        startMs: timestampToMs(timestamp),
        endMs: nextTimestamp ? timestampToMs(nextTimestamp) - 1 : undefined,
      };
    });
}

function parseJsonAssignment(html: string, variableName: string): unknown {
  const marker = `${variableName} =`;
  const startIndex = html.indexOf(marker);
  if (startIndex < 0) return undefined;
  const jsonStart = html.indexOf("{", startIndex);
  if (jsonStart < 0) return undefined;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = jsonStart; index < html.length; index += 1) {
    const char = html[index];
    if (!char) break;
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }
    if (char === "\"") {
      inString = true;
      continue;
    }
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) {
      try {
        return JSON.parse(html.slice(jsonStart, index + 1));
      } catch {
        return undefined;
      }
    }
  }
  return undefined;
}

function readUnknown(value: unknown, path: readonly (string | number)[]): unknown {
  let current: unknown = value;
  for (const key of path) {
    if (typeof key === "number") {
      if (!Array.isArray(current)) return undefined;
      current = current[key];
      continue;
    }
    if (typeof current !== "object" || current === null || !(key in current)) return undefined;
    current = (current as Record<string, unknown>)[key];
  }
  return current;
}

function readString(value: unknown, path: readonly (string | number)[]): string | undefined {
  const result = readUnknown(value, path);
  return typeof result === "string" ? result : undefined;
}

function readNestedArrayString(value: unknown, path: readonly (string | number)[]): string | undefined {
  const result = readUnknown(value, path);
  const firstItem = Array.isArray(result) ? result[0] : undefined;
  if (typeof firstItem !== "object" || firstItem === null || !("url" in firstItem)) return undefined;
  const url = (firstItem as Record<string, unknown>).url;
  return typeof url === "string"
    ? url
    : undefined;
}

function readXmlAttr(attributes: string, name: string): string | undefined {
  const match = new RegExp(`${name}="([^"]+)"`).exec(attributes);
  return match?.[1];
}

function stripTags(value: string): string {
  return value.replace(/<[^>]+>/g, "");
}

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, "\"")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

function timestampToMs(value: string): number {
  const parts = value.split(":").map((part) => Number.parseInt(part, 10));
  if (parts.some((part) => Number.isNaN(part))) return 0;
  if (parts.length === 2) {
    const [minutes = 0, seconds = 0] = parts;
    return (minutes * 60 + seconds) * 1000;
  }
  const [hours = 0, minutes = 0, seconds = 0] = parts;
  return ((hours * 60 + minutes) * 60 + seconds) * 1000;
}
